### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by AnaabTeam** [PapaTutuWawa/moxxyv2#15]
lib/service/omemo/omemo.dart:80:33: Error: The method 'call' isn't defined for the class 'bool'.
Try correcting the name to the name of an existing method, or defining a method named 'call'.
        await commitTrustManager(await omemoManager.trustManager.toJson());

**Comment by PapaTutuWawa** [comment]
Without any context, I cannot really do much. Maybe 84924b480b6d22a008d01f28e21b8a76833fc035 fixes the issue?

**Comment by AnaabTeam** [comment]
![image](https://user-images.githubusercontent.com/84382596/210876227-6feccc61-8657-42d4-8083-da0b51845c54.png)

**Comment by PapaTutuWawa** [comment]
I just tried it on my side and it builds with the newest commit from master.

**Comment by AnaabTeam** [comment]
Fixed!
but now I get this error when build for android:
![image](https://user-images.githubusercontent.com/84382596/210877174-16d97382-b4dd-41c9-939a-3da229affae9.png)

**Comment by PapaTutuWawa** [comment]
With what Java version are you using? I use Java 17 with which the build succeeds.

**Comment by AnaabTeam** [comment]
![image](https://user-images.githubusercontent.com/84382596/210877761-8228115d-b06a-4ea3-8f6e-03b24dfd9346.png)

**Comment by PapaTutuWawa** [comment]
Hmm... What is `flutter doctor` saying? Can you build other Flutter applications?

**Comment by AnaabTeam** [comment]
![image](https://user-images.githubusercontent.com/84382596/210878988-4bb792b5-0cb9-4488-bff5-f9ced93ec336.png)


Yes I can build other flutter projects!

**Comment by AnaabTeam** [comment]
Fixed by adding this line:
![image](https://user-images.githubusercontent.com/84382596/210880225-b48cbe0f-4e70-48c7-8345-41d05b283196.png)
