### ISSUE TITLE
Note: path is pinned to version 1.8.3 by flutter_localizations from the flutter SDK.

### ISSUE THREAD

**Issue by dnkls** [PapaTutuWawa/moxxyv2#17]
[moxxy] flutter pub get
Resolving dependencies...
Note: path is pinned to version 1.8.3 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

Because moxxyv2 depends on flutter_localizations from sdk which depends on path 1.8.3, path 1.8.3 is required.
So, because moxxyv2 depends on path 1.8.2, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Try an upgrade of your constraints: flutter pub upgrade --major-versions
exit code 1

**Comment by PapaTutuWawa** [comment]
For me with Flutter version `3.7.12`, I can run `flutter pub get` with no issues. Can you run `flutter doctor` and see if there are any issues? From what I can see, it seems like your Flutter version is too new and thus wants to pull in a newer version of `flutter_localization`.

**Comment by PapaTutuWawa** [comment]
Closing in favor of #18.
