### ISSUE TITLE
Issues while building Moxxy

### ISSUE THREAD

**Issue by dnkls** [PapaTutuWawa/moxxyv2#18]
! keyboard_height_plugin 0.0.5 (overridden)
  matcher 0.12.15 (0.12.16 available)
  material_color_utilities 0.5.0 (0.8.0 available)
! moxxmpp 0.4.0 from git https://codeberg.org/moxxy/moxxmpp.git at 864cc0 in packages/moxxmpp (overridden)

**Comment by PapaTutuWawa** [comment]
`keyboard_height_plugin` is overriden because I had to add a single commit to it. I am considering whether I just publish the fork to my pub repository or merge it into my platform library `moxplatform`.

`moxxmpp` is overridden because my XMPP library was evolving very quickly and I did not want to constantly release new versions of it.

Is there an issue with the overriddes?

**Comment by dnkls** [comment]
In general, when I load your project and make pub get I get a bunch of errors and moxxxy2 folders/packages are not loaded. I tried on vs code, intelij idea and Android studio. I get errors everywhere and dependencies are not loaded.

The errors start with :

path is pinned to version 1.8.3 by flutter_localizations from the flutter SDK.

And when I start to fix one, everything crumbles. Please help me, how to install your project correctly and where to install it.

**Comment by PapaTutuWawa** [comment]
The fact the Flutter/pub tells you that I override packages is not an error, but just a helpful "warning".

As mentioned in #17, I think your Flutter version is "too new" and thus wants to pull in a newer version of `flutter_localizations`, which then requires a newer version of `path`. My suggestion would be to either use a version management tool, like [fvm](https://github.com/fluttertools/fvm) (DISCLAIMER: I never used the tool; I only know of it), or you manually install an older version of Flutter somewhere else and use it. For this exact reason, I have my development setup pinned to Flutter 3.7.12 and have no issues with it. I do plan on upgrading all dependencies and the Flutter SDK to the newest release, but this will happen after I release Moxxy 0.5.0 (Which will probably be soon; See [here](https://codeberg.org/moxxy/moxxy/projects/2147) for the progress).

**EDIT**: Also, if you're interested, feel free to join the Moxxy [general Moxxy chat](xmpp:moxxy@muc.moxxy.org) and/or the [development chat](xmpp:dev@muc.moxxy.org).

**Comment by dnkls** [comment]
Okay, I'll install Flutter 3.7.12 and try it.  

P.s.
I'm a newbie, I came from Python when I couldn't find any normal xmpp client. I learned Java in a week when I saw all the XEPs I needed in Smack, but since the graphics in Android fx are terrible I have to learn flutter since the graphics there are very nice.

UPD: and by the way can you add this XEP https://xmpp.org/extensions/xep-0174.html ? 🤔🙃🫣

**Comment by dnkls** [comment]
I change flutter version like your 3.7.12 but see the seams error:

D:\myfolder\flutter\bin\flutter.bat --no-color pub get
Resolving dependencies...
Note: path is pinned to version 1.8.3 by integration_test from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because every version of integration_test from sdk depends on path 1.8.3 and moxxyv2 depends on path 1.8.2, integration_test from sdk is forbidden.
So, because moxxyv2 depends on integration_test from sdk, version solving failed.

**Comment by dnkls** [comment]
I solve above issue but get another :

Got dependencies!
Warning: You are using these overridden dependencies:
! keyboard_height_plugin 0.0.5
! moxxmpp 0.3.2 from git https://codeberg.org/moxxy/moxxmpp.git at 1475cb in packages/moxxmpp
Process finished with exit code 0

**Comment by PapaTutuWawa** [comment]
> Got dependencies!
> Warning: You are using these overridden dependencies:
> ! keyboard_height_plugin 0.0.5
> ! moxxmpp 0.3.2 from git https://codeberg.org/moxxy/moxxmpp.git at 1475cb in packages/moxxmpp
> Process finished with exit code 0

To me, that looks like everything went well.

**Comment by dnkls** [comment]
![IMG_1282](https://github.com/PapaTutuWawa/moxxy/assets/19364526/ba8baea1-e11b-4506-856f-17da257b7975)

**Comment by dnkls** [comment]
![IMG_1283](https://github.com/PapaTutuWawa/moxxy/assets/19364526/ef53e47f-8900-4838-bfab-579b05f99e27)
![IMG_1284](https://github.com/PapaTutuWawa/moxxy/assets/19364526/995c9bf5-52a0-4198-94a0-55bc9fbd4c3b)

**Comment by dnkls** [comment]
Unhandled exception:
Null check operator used on a null value
#0      IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:185:64)
#1      FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:721:46)
<asynchronous suspension>
#2      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:614:9)
<asynchronous suspension>
#3      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1222:11)
<asynchronous suspension>
Finished with error: the Dart compiler exited unexpectedly.
Failed to compile application.

**Comment by dnkls** [comment]
I think I understand, I can’t lunch it in chrome browser, I should lunch it in android device in intelij or android studio 🤔 but I’m not shure

**Comment by PapaTutuWawa** [comment]
Your first issue is probably caused by not running `flutter pub run build_runner build` before attempting to build Moxxy. The second issue is, as you've correctly identified, caused by the fact that Moxxy currently only supports Android.
